/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Negocio.DAOSalaException;
import Negocio.FachadaServicoTmdb;
import Negocio.FachadaServicoTmdbException;
import Negocio.Filme;
import Negocio.FilmeDAO;
import Negocio.Horario;
import Negocio.HorarioDAO;
import Negocio.Sala;
import Negocio.SalaDAO;
import Persistencia.HorarioDAODerby;
import Persistencia.SalaDAODerby;
import com.omertron.themoviedbapi.TheMovieDbApi;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ingridlouisepanizzirodrigues
 */
public class GerenciarSessoes extends javax.swing.JFrame {
    private static TheMovieDbApi tmdb;
    String chave = "7f33d776068a7e8045c703100347fd69";
    MyComboModelMovieDB comboFilmes;
    FachadaServicoTmdb fachada;
    FilmeDAO filmeDAOFilmes;
    SalaDAODerby salaDAOFilmes = new SalaDAODerby();
    HorarioDAODerby horarioDAOFilmes = new HorarioDAODerby();
    
    public GerenciarSessoes() throws FachadaServicoTmdbException {
        initComponents();
        fachada = new FachadaServicoTmdb(chave);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdicionarSessao = new javax.swing.JButton();
        lblSala = new javax.swing.JLabel();
        lblHorario = new javax.swing.JLabel();
        ddlSala = new javax.swing.JComboBox();
        ddlHorario = new javax.swing.JComboBox();
        lblFilme = new javax.swing.JLabel();
        btnInfoFilmes = new javax.swing.JButton();
        ddlFilmes = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAdicionarSessao.setText("Adicionar Sessão");
        btnAdicionarSessao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarSessaoActionPerformed(evt);
            }
        });

        lblSala.setText("Sala");

        lblHorario.setText("Horário");

        ddlSala.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ddlHorario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblFilme.setText("Selecionar o Filme:");

        btnInfoFilmes.setText("Carregar Informações de Filmes");
        btnInfoFilmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoFilmesActionPerformed(evt);
            }
        });

        ddlFilmes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addComponent(lblFilme)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSala)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ddlSala, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(lblHorario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ddlHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ddlFilmes, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdicionarSessao)
                        .addGap(247, 247, 247)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(btnInfoFilmes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(btnInfoFilmes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFilme)
                    .addComponent(ddlFilmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSala)
                    .addComponent(lblHorario)
                    .addComponent(ddlSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ddlHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAdicionarSessao)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarSessaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarSessaoActionPerformed
        
    }//GEN-LAST:event_btnAdicionarSessaoActionPerformed

    private void btnInfoFilmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoFilmesActionPerformed
        MyComboModelFilme comboFilmes;
        MyComboModelSalas comboSalas;
        MyComboModelHorarios comboHorarios;
        List<Filme> filmes = fachada.getFilmes();
        List<Sala> salas = new ArrayList<>();
        salas = salaDAOFilmes.getSalas();
        List<Horario> horarios = new ArrayList<>();
        horarios = horarioDAOFilmes.getHorarios();
        /*
        List<Sala> salas = fachada.getSalas();
        
        if(salas.isEmpty()){
            JOptionPane.showMessageDialog(null, "Nenhuma sala encontrada", "Erro", WIDTH, null);
        }else{
            comboFilmes = new MyComboModelFilme(filmes);
            jComboBox1.removeAllItems();
            jComboBox1.setModel(comboFilmes);
        }*/
        
        if(filmes.isEmpty()){
            JOptionPane.showMessageDialog(null, "Nenhum filme encontrado", "Erro", WIDTH, null);
        }else{
            comboFilmes = new MyComboModelFilme(filmes);
            ddlFilmes.removeAllItems();
            ddlFilmes.setModel(comboFilmes);
            comboSalas = new MyComboModelSalas(salas);
            ddlSala.removeAllItems();
            ddlSala.setModel(comboSalas);
            comboHorarios = new MyComboModelHorarios(horarios);
            ddlHorario.removeAllItems();
            ddlHorario.setModel(comboHorarios);
        }
    }//GEN-LAST:event_btnInfoFilmesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarSessoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarSessoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarSessoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarSessoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GerenciarSessoes().setVisible(true);
                } catch (FachadaServicoTmdbException ex) {
                    Logger.getLogger(GerenciarSessoes.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarSessao;
    private javax.swing.JButton btnInfoFilmes;
    private javax.swing.JComboBox ddlFilmes;
    private javax.swing.JComboBox ddlHorario;
    private javax.swing.JComboBox ddlSala;
    private javax.swing.JLabel lblFilme;
    private javax.swing.JLabel lblHorario;
    private javax.swing.JLabel lblSala;
    // End of variables declaration//GEN-END:variables
}
